apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-api
  labels:
    app:  webinar-api
    version: v1
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  webinar-api
      version: v1
      type: backend
  template:
    metadata:
      labels:
        app:  webinar-api
        version: v1
        type: backend
    spec:
      containers:
      - image:  webinar-api:latest
        imagePullPolicy: IfNotPresent
        name:  webinar-api
        resources:
          requests:
            cpu: "150m"
            memory: "250M"
          limits:
            cpu: "1"
            memory: "750M"
        readinessProbe:
          httpGet:
            path: /values
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10     
        ports:
        - containerPort:  8080
          name:  webinar-api

---

kind: Service
apiVersion: v1
metadata:
  name:  webinar-api-service
spec:
  selector:
    app:  webinar-api
    version: v1
    type: backend
  type:  ClusterIP
  ports:
  - port:  8080
    targetPort:  8080
      