apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: my-nginx-app
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80